apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: panduboyina/bankingapp-2.0-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: "http"
            - containerPort: 5005
              name: "debug"